---
title: "Folate_ConMF_Placentas"
output: html_document
date: "2023-12-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load RNA-sequencing data
```{r}
library(WGCNA)
library(readxl)

#only use samples that have 
#No PCB ; No Folic Acid (0 / No)
#No PCB ; Yes Folic Acid (0 / Yes)
#Yes PCB ; No Folic Acid (0.1 / No)
#Yes PCB ; Yes Folic Acid (0.1 / Yes)
#so take out samples that have 1PCB/6PCB (Groups C and D)

F_Placenta <- read_excel("/Users/kchau/Documents/PEBBLES/Folate_ConMF_Placentas/F_Placenta_FA.xlsx")
F_Placenta <- F_Placenta[!grepl("BRAIN", colnames(F_Placenta))]

M_Placenta <- read_excel("/Users/kchau/Documents/PEBBLES/Folate_ConMF_Placentas/M_Placenta_FA.xlsx")
M_Placenta <- M_Placenta[!grepl("BRAIN", colnames(M_Placenta))]

# Take a quick look at what is in the data sets (caution, longish output):
dim(F_Placenta)
names(F_Placenta)
dim(M_Placenta)
names(M_Placenta)
```

```{r}
intersectedgenes <- intersect(rownames(F_Placenta), rownames(M_Placenta))
F_Placenta1 <- F_Placenta[intersectedgenes, ]
M_Placenta1 <- M_Placenta[intersectedgenes, ]
```

```{r}
# We work with two sets:
nSets = 2;
# For easier labeling of plots, create a vector holding descriptive names of the two sets.
setLabels = c("Female placenta", "Male placenta")
shortLabels = c("Female", "Male")
# Form multi-set expression data
multiExpr = vector(mode = "list", length = nSets)
multiExpr[[1]] = list(data = as.data.frame(t(F_Placenta1[-c(1:1)])));
names(multiExpr[[1]]$data) = F_Placenta1$Gene;
rownames(multiExpr[[1]]$data) = names(F_Placenta1)[-c(1:1)];
multiExpr[[2]] = list(data = as.data.frame(t(M_Placenta1[-c(1:1)])));
names(multiExpr[[2]]$data) = M_Placenta1$Gene;
rownames(multiExpr[[2]]$data) = names(M_Placenta1)[-c(1:1)];
```

```{r}
# Check that the data has the correct format for many functions operating on multiple sets:
exprSize = checkSets(multiExpr)
```

```{r}
# Check that all genes and samples have sufficiently low numbers of missing values.
gsg = goodSamplesGenesMS(multiExpr, verbose = 3);
gsg$allOK
```


```{r}
if (!gsg$allOK)
{
# Print information about the removed genes:
if (sum(!gsg$goodGenes) > 0)
printFlush(paste("Removing genes:", paste(names(multiExpr[[1]]$data)[!gsg$goodGenes],
collapse = ", ")))
for (set in 1:exprSize$nSets)
{

if (sum(!gsg$goodSamples[[set]]))
printFlush(paste("In set", setLabels[set], "removing samples",
paste(rownames(multiExpr[[set]]$data)[!gsg$goodSamples[[set]]], collapse = ", ")))
# Remove the offending genes and samples
multiExpr[[set]]$data = multiExpr[[set]]$data[gsg$goodSamples[[set]], gsg$goodGenes];
}
# Update exprSize
exprSize = checkSets(multiExpr)
}
```

```{r}
sampleTrees = list()
for (set in 1:nSets)
{
sampleTrees[[set]] = hclust(dist(multiExpr[[set]]$data), method = "average")
}
```

```{r}
pdf(file = "/Users/kchau/Documents/WGCNA/ConsensusPlacentaComparisonFolicAcid/SamplesClustering.pdf", width = 12, height = 12);
par(mfrow=c(2,1))
par(mar = c(0, 4, 2, 0))
for (set in 1:nSets)
plot(sampleTrees[[set]], main = paste("Sample clustering on all genes in", setLabels[set]),
xlab="", sub="", cex = 0.7);
dev.off()
```

```{r}
collectGarbage();
# Check the size of the leftover data
exprSize = checkSets(multiExpr)
exprSize
```


```{r}
FolatetraitData = read_excel("/Users/kchau/Documents/PEBBLES/sampletraits/FolicAcidM_F_Placenta_combinations.xlsx")
dim(FolatetraitData)
names(FolatetraitData)
```


```{r}
FAallTraits = FolatetraitData
# See how big the traits are and what are the trait and sample names
dim(FAallTraits)
names(FAallTraits)
FAallTraits$Name
```

```{r}
FAallTraits <- FAallTraits[, -c(4)]
```


```{r}
FAallTraits <- FAallTraits[, -c(3, 5, 6, 8)]
```



```{r}
#FA
# Form a multi-set structure that will hold the sample traits.
FATraits = vector(mode="list", length = nSets);
for (set in 1:nSets)
{
FAsetSamples = rownames(multiExpr[[set]]$data);
FAtraitRows = match(FAsetSamples, FAallTraits$Name);
FATraits[[set]] = list(data = FAallTraits[FAtraitRows, -1]);
rownames(FATraits[[set]]$data) = as.data.frame(FAallTraits)[FAtraitRows, 1]
#rownames(PCBTraits[[set]]$data) = as.data.frame(PCBallTraits)[PCBtraitRows, 1];
}
collectGarbage();
# Define data set dimensions
FAnGenes = exprSize$nGenes;
FAnSamples = exprSize$nSamples;
```

```{r}
# Choose a set of soft-thresholding powers
powers = c(seq(4,10,by=1), seq(12,40, by=2));
# Initialize a list to hold the results of scale-free analysis
powerTables = vector(mode = "list", length = nSets);
# Call the network topology analysis function for each set in turn
for (set in 1:nSets)
powerTables[[set]] = list(data = pickSoftThreshold(multiExpr[[set]]$data, powerVector=powers,
verbose = 2)[[2]]);
collectGarbage();
# Plot the results:
colors = c("black", "red")
# Will plot these columns of the returned scale free analysis tables
plotCols = c(2,5,6,7)
colNames = c("Scale Free Topology Model Fit", "Mean connectivity", "Median connectivity",
"Max connectivity");
# Get the minima and maxima of the plotted points
ylim = matrix(NA, nrow = 2, ncol = 4);
for (set in 1:nSets)
{
for (col in 1:length(plotCols))

{
ylim[1, col] = min(ylim[1, col], powerTables[[set]]$data[, plotCols[col]], na.rm = TRUE);
ylim[2, col] = max(ylim[2, col], powerTables[[set]]$data[, plotCols[col]], na.rm = TRUE);
}
}
# Plot the quantities in the chosen columns vs. the soft thresholding power
sizeGrWindow(8, 6)
pdf(file = "/Users/kchau/Documents/WGCNA/ConsensusPlacentaComparisonFolicAcid/scaleFreeAnalysis.pdf", wi = 8, he = 6)
par(mfcol = c(2, 2));
par(mar = c(4, 4 , 2, 0.3))
cex1 = 0.7;
for (col in 1:length(plotCols)) for (set in 1:nSets)
{
if (set==1)
{
plot(powerTables[[set]]$data[,1], -sign(powerTables[[set]]$data[,3])*powerTables[[set]]$data[,2],
xlab="Soft Threshold (power)",ylab=colNames[col],type="n", ylim = ylim[, col],
main = colNames[col]);
addGrid();
}
if (col==1)
{
text(powerTables[[set]]$data[,1], -sign(powerTables[[set]]$data[,3])*powerTables[[set]]$data[,2],
labels=powers,cex=cex1,col=colors[set]);
} else
text(powerTables[[set]]$data[,1], powerTables[[set]]$data[,plotCols[col]],
labels=powers,cex=cex1,col=colors[set]);
if (col==1)
{
legend("bottomright", legend = setLabels, col = colors, pch = 20) ;
} else
legend("topright", legend = setLabels, col = colors, pch = 20) ;
}
dev.off();
```

#increase minModuleSize to minimize number of modules
```{r}
bnet = blockwiseConsensusModules(
multiExpr, maxBlockSize = FAnGenes, power = 28, minModuleSize = 150,
corTtype = "bicor", 
networkType = "signed",
TOMType = "signed",
deepSplit = 2,
pamRespectsDendro = FALSE,
mergeCutHeight = 0.25, numericLabels = TRUE,
minKMEtoStay = 0,
saveTOMs = TRUE, verbose = 5)
```

```{r}
FAconsMEs = bnet$multiMEs;
FAmoduleLabels = bnet$colors;
# Convert the numeric labels to color labels
FAmoduleColors = labels2colors(FAmoduleLabels)
FAconsTree = bnet$dendrograms[[1]]
```

```{r}
sizeGrWindow(12,6)

pdf(file = "/Users/kchau/Documents/WGCNA/ConsensusPlacentaComparisonFolicAcid/FABlockwiseGeneDendrosAndColors.pdf", wi = 12, he = 6);
# Use the layout function for more involved screen sectioning
layout(matrix(c(1:4), 2, 2), heights = c(0.8, 0.2), widths = c(1,1))
#layout.show(4);
nBlocks = length(bnet$dendrograms)
# Plot the dendrogram and the module colors underneath for each block
for (block in 1:nBlocks)
plotDendroAndColors(bnet$dendrograms[[block]], FAmoduleColors[bnet$blockGenes[[block]]],
"Module colors",
main = paste("Consensus Placenta Gene dendrogram and module colors in block", block),
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05,
setLayout = FALSE)
dev.off()
```


```{r}
#find number of modules
table(bnet$colors)
```


```{r}
# Set up variables to contain the module-trait correlations
FAmoduleTraitCor = list();
FAmoduleTraitPvalue = list();
# Calculate the correlations
for (set in 1:nSets)
{
FAmoduleTraitCor[[set]] = cor(FAconsMEs[[set]]$data, FATraits[[set]]$data, use = "p", method = "spearman");
FAmoduleTraitPvalue[[set]] = corPvalueFisher(FAmoduleTraitCor[[set]], exprSize$nSamples[set])
}
```

```{r}
# # Convert numerical lables to colors for labeling of modules in the plot
# FAMEColors = labels2colors(as.numeric(substring(names(FAconsMEs[[1]]$data), 3)));
# FAMEColorNames = paste("ME", FAMEColors, sep="");
# #lookup_table = data.frame(color=FAMEColors, label=paste("Module", 1:length(FAMEColors), "Placenta"), colornames = paste("Module", "Placenta", FAMEColors));
# lookup_table = data.frame(color=FAMEColors, label=paste("M",1:length(FAMEColors), "MFPlac"));
# # Open a suitably sized window (the user should change the window size if necessary)
# sizeGrWindow(11,9)
# pdf(file = "/Users/kchau/Documents/WGCNA/ConsensusPlacentaComparisonFolicAcid/ConsensusModuleTraitRelationships-FAfemale.pdf", wi = 7, he = 10);
# # Plot the module-trait relationship table for set number 1
# set = 1
# textMatrix = paste(signif(FAmoduleTraitCor[[set]], 2), "\n(",
# signif(FAmoduleTraitPvalue[[set]], 1), ")", sep = "");
# dim(textMatrix) = dim(FAmoduleTraitCor[[set]])
# par(mar = c(6, 8.8, 3, 2.2));
# labeledHeatmap(Matrix = FAmoduleTraitCor[[set]],
# xLabels = names(FATraits[[set]]$data),
# yLabels = lookup_table$label,
# ySymbols = FAMEColorNames,
# colorLabels = FALSE,
# colors = greenWhiteRed(50),
# textMatrix = textMatrix,
# setStdMargins = FALSE,
# cex.text = 0.8,
# zlim = c(-1,1),
# main = paste("Module Eigengene Relationship with FA Dose in", setLabels[set]))
# dev.off();
# # Plot the module-trait relationship table for set number 2
# set = 2
# textMatrix = paste(signif(FAmoduleTraitCor[[set]], 2), "\n(",
# signif(FAmoduleTraitPvalue[[set]], 1), ")", sep = "");
# dim(textMatrix) = dim(FAmoduleTraitCor[[set]])
# sizeGrWindow(11,9)
# pdf(file = "/Users/kchau/Documents/WGCNA/ConsensusPlacentaComparisonFolicAcid/ConsensusModuleTraitRelationships-FAmale.pdf", wi = 7, he = 10);
# par(mar = c(6, 8.8, 3, 2.2));
# labeledHeatmap(Matrix = FAmoduleTraitCor[[set]],
# xLabels = names(FATraits[[set]]$data),
# yLabels = FAMEColorNames,
# ySymbols = FAMEColorNames,
# colorLabels = FALSE,
# colors = greenWhiteRed(50),
# textMatrix = textMatrix,
# setStdMargins = FALSE,
# cex.text = 0.8,
# zlim = c(-1,1),
# main = paste("Module Eigengene Relationship with FA Dose in", setLabels[set]))
# dev.off()
```


```{r}
# Convert numerical lables to colors for labeling of modules in the plot
FAMEColors = labels2colors(as.numeric(substring(names(FAconsMEs[[1]]$data), 3)));
FAMEColorNames = paste("ME", FAMEColors, sep="");
#lookup_table = data.frame(color=FAMEColors, label=paste("Module", 1:length(FAMEColors), "Placenta"), colornames = paste("Module", "Placenta", FAMEColors));
#lookup_table = data.frame(color=FAMEColors, label=paste("M",1:length(FAMEColors), "MFPlac"));
# Open a suitably sized window (the user should change the window size if necessary)
sizeGrWindow(11,9)
pdf(file = "/Users/kchau/Documents/WGCNA/ConsensusPlacentaComparisonFolicAcid/ConsensusModuleTraitRelationships-bicor-FAfemale-twocolumn.pdf", wi = 4, he = 10);
# Plot the module-trait relationship table for set number 1
set = 1
textMatrix = paste(signif(FAmoduleTraitCor[[set]], 2), "\n(",
signif(FAmoduleTraitPvalue[[set]], 1), ")", sep = "");
dim(textMatrix) = dim(FAmoduleTraitCor[[set]])
par(mar = c(6, 8.8, 3, 2.2));
labeledHeatmap(Matrix = FAmoduleTraitCor[[set]],
xLabels = names(FATraits[[set]]$data),
yLabels = FAMEColorNames,
ySymbols = FAMEColorNames,
colorLabels = FALSE,
colors = blueWhiteRed(50),
textMatrix = textMatrix,
setStdMargins = FALSE,
cex.text = 0.8,
zlim = c(-1,1),
main = paste("Module Eigengene Relationship with FA Dose in", setLabels[set]))
dev.off();
# Plot the module-trait relationship table for set number 2
set = 2
textMatrix = paste(signif(FAmoduleTraitCor[[set]], 2), "\n(",
signif(FAmoduleTraitPvalue[[set]], 1), ")", sep = "");
dim(textMatrix) = dim(FAmoduleTraitCor[[set]])
sizeGrWindow(11,9)
pdf(file = "/Users/kchau/Documents/WGCNA/ConsensusPlacentaComparisonFolicAcid/ConsensusModuleTraitRelationships-bicor-FAmale-twocolumn.pdf", wi = 4, he = 10);
par(mar = c(6, 8.8, 3, 2.2));
labeledHeatmap(Matrix = FAmoduleTraitCor[[set]],
xLabels = names(FATraits[[set]]$data),
yLabels = FAMEColorNames,
ySymbols = FAMEColorNames,
colorLabels = FALSE,
colors = blueWhiteRed(50),
textMatrix = textMatrix,
setStdMargins = FALSE,
cex.text = 0.8,
zlim = c(-1,1),
main = paste("Module Eigengene Relationship with FA Dose in", setLabels[set]))
dev.off()
```

```{r}
# Initialize matrices to hold the consensus correlation and p-value
FAconsensusCor = matrix(NA, nrow(FAmoduleTraitCor[[1]]), ncol(FAmoduleTraitCor[[1]]));
FAconsensusPvalue = matrix(NA, nrow(FAmoduleTraitCor[[1]]), ncol(FAmoduleTraitCor[[1]]));
# Find consensus negative correlations
FAnegative = FAmoduleTraitCor[[1]] < 0 & FAmoduleTraitCor[[2]] < 0;
FAconsensusCor[FAnegative] = pmax(FAmoduleTraitCor[[1]][FAnegative], FAmoduleTraitCor[[2]][FAnegative]);
FAconsensusPvalue[FAnegative] = pmax(FAmoduleTraitPvalue[[1]][FAnegative], FAmoduleTraitPvalue[[2]][FAnegative]);
# Find consensus positive correlations
FApositive = FAmoduleTraitCor[[1]] > 0 & FAmoduleTraitCor[[2]] > 0;
FAconsensusCor[FApositive] = pmin(FAmoduleTraitCor[[1]][FApositive], FAmoduleTraitCor[[2]][FApositive]);
FAconsensusPvalue[FApositive] = pmax(FAmoduleTraitPvalue[[1]][FApositive], FAmoduleTraitPvalue[[2]][FApositive])
```

```{r}
textMatrix = paste(signif(FAconsensusCor, 2), "\n(",
signif(FAconsensusPvalue, 1), ")", sep = "");
dim(textMatrix) = dim(FAmoduleTraitCor[[set]])
sizeGrWindow(10,7)
pdf(file = "/Users/kchau/Documents/WGCNA/ConsensusPlacentaComparisonFolicAcid/ModuleTraitRelationships-bicor-FAconsensus.pdf", wi = 6, he = 15);
par(mar = c(6, 8.8, 3, 2.2));
labeledHeatmap(Matrix = FAconsensusCor,
xLabels = names(FATraits[[set]]$data),
yLabels = FAMEColorNames,
ySymbols = FAMEColorNames,
colorLabels = FALSE,
colors = blueWhiteRed(50),
textMatrix = textMatrix,
setStdMargins = FALSE,
cex.text = 0.7,
zlim = c(-1,1),
main = paste("Consensus module FA trait relationships across\n",
paste(setLabels, collapse = " and ")))
```

```{r}
# Create a variable weight that will hold just the Folic Acid trait of mice in both sets
FADose = vector(mode = "list", length = nSets);
for (set in 1:nSets)
{
FADose[[set]] = list(data = as.data.frame(FATraits[[set]]$data$Folic_Acid));
names(FADose[[set]]$data) = "Folic Acid"
}
# Recalculate consMEs to give them color names
consMEsC = multiSetMEs(multiExpr, universalColors = FAmoduleColors);
# We add the weight trait to the eigengenes and order them by consesus hierarchical clustering:
MET = consensusOrderMEs(addTraitToMEs(consMEsC, FADose))
```
```{r}
sizeGrWindow(8,10);
pdf(file = "/Users/kchau/Documents/WGCNA/ConsensusPlacentaComparisonFolicAcid/FAEigengeneNetworks.pdf", width= 15, height = 16);
par(cex = 1)
plotEigengeneNetworks(MET, setLabels, marDendro = c(0,2,2,1), marHeatmap = c(7,7,7,7), setMargins = TRUE,
zlimPreservation = c(0.5, 1), xLabelsAngle = 90)
dev.off()
```


```{r}
library("AnnotationDbi")
library("org.Mm.eg.db")
#columns(org.Mm.eg.db) # returns list of available keytypes
F_Placenta1$entrez = mapIds(org.Mm.eg.db,
                    keys=F_Placenta1$Gene, #Column containing Ensembl gene ids
                    column="ENTREZID",
                    keytype="ENSEMBL",
                    multiVals="first")
```

```{r}
#columns(org.Mm.eg.db) # returns list of available keytypes
M_Placenta1$entrez = mapIds(org.Mm.eg.db,
                    keys=M_Placenta1$Gene, #Column containing Ensembl gene ids
                    column="ENTREZID",
                    keytype="ENSEMBL",
                    multiVals="first")
```


```{r}
#GO Terms Female Placenta
GOenrFemalePlacenta = GOenrichmentAnalysis(FAmoduleColors, F_Placenta1$entrez, organism = "mouse", evidence = "all", nBestP = 10)

#GO Terms Male Placenta
GOenrMalePlacenta = GOenrichmentAnalysis(FAmoduleColors, M_Placenta1$entrez, organism = "mouse", evidence = "all", nBestP = 10)
```


```{r}
tabFemalePlacenta = GOenrFemalePlacenta$bestPTerms[[4]]$enrichment
tabMalePlacenta = GOenrMalePlacenta$bestPTerms[[4]]$enrichment
```

#For Consensus GO terms
```{r}
consMEs.unord = multiSetMEs(multiExpr, universalColors = FAmoduleLabels, excludeGrey = TRUE)
GS = list();
kME = list();
for (set in 1:nSets)
{
GS[[set]] = corAndPvalue(multiExpr[[set]]$data, FATraits[[set]]$data);
kME[[set]] = corAndPvalue(multiExpr[[set]]$data, consMEs.unord[[set]]$data);
}
```

```{r}
#find number of genes in each module
genes_per_module <- table(FAmoduleColors)


```

```{r}
install.packages("formattable")
install.packages("data.table")
install.packages("dplyr")
install.packages("tidyr")
library(data.table)
library(dplyr)
library(formattable)
library(tidyr)
```

```{r}
#orders from lowest number of genes to highest
genes_per_module <- arrange(data.frame(genes_per_module), Freq)

formattable(genes_per_module)
knitr::kable(genes_per_module, format = "html", col.names = c("Module", "Number of Genes"))

```

```{r}
#orders from lowest number of genes to highest
genes_per_module1 <- genes_per_module[match(lookup_table$color, data.frame(genes_per_module)$FAmoduleColors),]

formattable(genes_per_module1)
knitr::kable(genes_per_module1, format = "html", col.names = c("Module", "Number of Genes"))

```


```{r}
GS.metaZ = (GS[[1]]$Z + GS[[2]]$Z)/sqrt(2);
kME.metaZ = (kME[[1]]$Z + kME[[2]]$Z)/sqrt(2);
GS.metaP = 2*pnorm(abs(GS.metaZ), lower.tail = FALSE);
kME.metaP = 2*pnorm(abs(kME.metaZ), lower.tail = FALSE)
```

```{r}
GSmat = rbind(GS[[1]]$cor, GS[[2]]$cor, GS[[1]]$p, GS[[2]]$p, GS.metaZ, GS.metaP);
nTraits = checkSets(FATraits)$nGenes
traitNames = colnames(FATraits[[1]]$data)
dim(GSmat) = c(FAnGenes, 6*nTraits)
#rownames(GSmat) = probes;
rownames(GSmat) = M_Placenta1$Gene;
colnames(GSmat) = spaste(
c("GS.set1.", "GS.set2.", "p.GS.set1.", "p.GS.set2.", "Z.GS.meta.", "p.GS.meta"),
rep(traitNames, rep(6, nTraits)))
# Same code for kME:
kMEmat = rbind(kME[[1]]$cor, kME[[2]]$cor, kME[[1]]$p, kME[[2]]$p, kME.metaZ, kME.metaP);
MEnames = colnames(consMEs.unord[[1]]$data);
nMEs = checkSets(consMEs.unord)$nGenes
dim(kMEmat) = c(FAnGenes, 6*nMEs)
#rownames(kMEmat) = probes;
rownames(kMEmat) = M_Placenta1$Gene;
colnames(kMEmat) = spaste(
c("kME.set1.", "kME.set2.", "p.kME.set1.", "p.kME.set2.", "Z.kME.meta.", "p.kME.meta"),
rep(MEnames, rep(6, nMEs)))
```


```{r}
info = data.frame(Probe = M_Placenta1$Gene, EntrezID = M_Placenta1$entrez,
ModuleLabel = FAmoduleLabels,
ModuleColor = labels2colors(FAmoduleLabels), GSmat, kMEmat);
write.csv(info, file = "/Users/kchau/Documents/WGCNA/ConsensusPlacentaComparisonFolicAcid/placenta_consensusAnalysis-CombinedNetworkResults.csv",
row.names = FALSE, quote = FALSE)
```


```{r}
info <- info[, 1:4]
info$GeneSymbol <- 'NA'

#Convert entrezID to gene symbols using biomart
library(biomaRt)
library(dplyr)
#library(xlsx)


mart <- useDataset("mmusculus_gene_ensembl", useMart("ensembl"))
#got the probe and gene symbol that matches
geneSymbols <- getBM(filters = "ensembl_gene_id", attributes= c("ensembl_gene_id", "external_gene_name"), values=info$Probe, mart= mart)

#join the dataframe with moduleinfo by Probe column
joinGeneSymbol <- left_join(info, geneSymbols, by = c("Probe" = "ensembl_gene_id"))
```

```{r}
kMEcols <- grep("^Z.kME.meta", colnames(info), value = TRUE)

hubTable <- do.call(rbind, lapply(kMEcols, function(colname) {

  ME <- sub("^Z.kME.meta.", "", colname)

  # extract numeric ME index (ME1 -> 1)
  MEidx <- as.numeric(sub("^ME", "", ME))

  # genes assigned to this module by clustering
  genesInModule <- info$ModuleLabel == MEidx

  if (!any(genesInModule)) return(NULL)

  zvals <- as.numeric(info[[colname]])

  info[genesInModule, ][
    which.max(abs(zvals[genesInModule])),
  ]
}))

```

```{r}
joinGeneSymbol <- joinGeneSymbol[ , -c(5:125)]
```


```{r}
library(enrichR)
#split function
modulecolors_split <- split(joinGeneSymbol, joinGeneSymbol$ModuleColor)


# Assuming you have a list of module colors and their corresponding data frames
#module_colors <- c('red', 'blue', 'green', ...)  # Add other module colors as needed
#module_data_frames <- list(red = redmodule, blue = bluemodule, green = greenmodule, ...)  # Replace with actual data frames for other modules

# Create a function to perform enrichment analysis and save the results
perform_enrichment <- function(module_color, module_data) {
  enriched_data <- enrichR::enrichr(
    module_data$external_gene_name,
    c('GO_Biological_Process_2023', 'GO_Cellular_Component_2023', 'GO_Molecular_Function_2023', 'KEGG_2021_Human')
  )
  file_path <- sprintf("/Users/kchau/Documents/WGCNA/ConsensusPlacentaComparisonFolicAcid/GO_terms/%s_excel.xlsx", module_color)
  openxlsx::write.xlsx(enriched_data, file_path)
}

# Loop through each module color and perform enrichment analysis
for (color in names(modulecolors_split)) {
  module_data <- modulecolors_split[[color]]
  perform_enrichment(color, module_data)
}
```

```{r}
library(enrichR)
#split function
modulecolors_split <- split(joinGeneSymbol, joinGeneSymbol$ModuleColor)


# Assuming you have a list of module colors and their corresponding data frames
#module_colors <- c('red', 'blue', 'green', ...)  # Add other module colors as needed
#module_data_frames <- list(red = redmodule, blue = bluemodule, green = greenmodule, ...)  # Replace with actual data frames for other modules

# Create a function to perform enrichment analysis and save the results
perform_enrichment <- function(module_color, module_data) {
  enriched_data <- enrichR::enrichr(
    module_data$external_gene_name,
    c('CellMarker_2024')
  )
  file_path <- sprintf("/Users/kchau/Documents/WGCNA/ConsensusPlacentaComparisonFolicAcid/CellMarkerEnrichments/%s_excel.xlsx", module_color)
  openxlsx::write.xlsx(enriched_data, file_path)
}

# Loop through each module color and perform enrichment analysis
for (color in names(modulecolors_split)) {
  module_data <- modulecolors_split[[color]]
  perform_enrichment(color, module_data)
}
```















```{r}
save(list = ls(.GlobalEnv), file = "/Users/kchau/Documents/WGCNA/ConsensusPlacentaComparisonFolicAcid/Renv.Rdata")
```



```{r}
library(ggplot2)
library(glue)
library(tidyr)
library(viridis)
library(dplyr)
library(readxl)
GOfiles <- "/Users/kchau/Documents/WGCNA/ConsensusPlacentaComparisonFolicAcid/GO_terms/"

#Similar MODULES

Blue <- read_excel(glue::glue("{GOfiles}/blue_excel.xlsx"), sheet = "KEGG_2021_Human")
Blue$Sample <- "Blue"

Grey60 <- read_excel(glue::glue("{GOfiles}/grey60_excel.xlsx"), sheet = "KEGG_2021_Human")
Grey60$Sample <- "Grey60"

Greenyellow <- read_excel(glue::glue("{GOfiles}/greenyellow_excel.xlsx"), sheet = "KEGG_2021_Human")
Greenyellow$Sample <- "Greenyellow"
```

```{r}
GOdf <- rbind(Blue, Grey60, Greenyellow)
GOdf <- GOdf %>% 
  dplyr::select(Sample, Term, Adjusted.P.value, Odds.Ratio) %>%
  group_by(Sample) %>%
  slice_min(order_by = Adjusted.P.value, n = 10)


significantGO <- GOdf[GOdf$Adjusted.P.value < 0.05, ]
```

```{r}
ggplot(significantGO,
       aes(x = Term, y = Sample, color = Adjusted.P.value, size = Odds.Ratio)) +
  geom_point() +
  scale_size(range = c(2.5,12.5)) +
  scale_color_viridis() +
  xlab('') + ylab('Module') +
  labs(
    title = 'KEGG Terms from Modules Similar\nbetween Male and Female Placenta'
  )  +   
  theme_bw(base_size = 22) +
  theme(
    legend.position = 'right',
    legend.background = element_rect(),
    plot.title = element_text(angle = 0, size = 16, face = 'bold', vjust = 0),
    plot.subtitle = element_text(angle = 0, size = 14, face = 'bold', vjust = 1),
    plot.caption = element_text(angle = 0, size = 12, face = 'bold', vjust = 1),
    
    axis.text.x = element_text(angle = 90, size = 14, face = 'bold', hjust = 1.0, vjust = 0.5),
    axis.text.y = element_text(angle = 0, size = 12, face = 'bold', vjust = 0.5),
    axis.title = element_text(size = 14, face = 'bold'),
    axis.title.x = element_text(size = 14, face = 'bold'),
    axis.title.y = element_text(size = 14, face = 'bold'),
    axis.line = element_line(colour = 'black'),
    
    #Legend
    legend.key = element_blank(), # removes the border
    legend.key.size = unit(1, "cm"), # Sets overall area/size of the legend
    legend.text = element_text(size = 14, face = "bold"), # Text size
    title = element_text(size = 14, face = "bold")) +
  coord_flip()
```


```{r}
#Different MODULES

Cyan <- read_excel(glue::glue("{GOfiles}/cyan_excel.xlsx"), sheet = "KEGG_2021_Human")
Cyan$Sample <- "Cyan"


Pink <- read_excel(glue::glue("{GOfiles}/pink_excel.xlsx"), sheet = "KEGG_2021_Human")
Pink$Sample <- "Pink"
```

```{r}
GOdf <- rbind(Cyan, Pink)
GOdf <- GOdf %>% 
  dplyr::select(Sample, Term, Adjusted.P.value, Odds.Ratio) %>%
  group_by(Sample) %>%
  slice_min(order_by = Adjusted.P.value, n = 10)


significantGO <- GOdf[GOdf$Adjusted.P.value < 0.05, ]
```

```{r}
ggplot(significantGO,
       aes(x = Term, y = Sample, color = Adjusted.P.value, size = Odds.Ratio)) +
  geom_point() +
  scale_size(range = c(2.5,12.5)) +
  scale_color_viridis() +
  xlab('') + ylab('Module') +
  labs(
    title = 'KEGG Terms from Modules Different\nbetween Male and Female Placenta'
  )  +   
  theme_bw(base_size = 22) +
  theme(
    legend.position = 'right',
    legend.background = element_rect(),
    plot.title = element_text(angle = 0, size = 16, face = 'bold', vjust = 0),
    plot.subtitle = element_text(angle = 0, size = 14, face = 'bold', vjust = 1),
    plot.caption = element_text(angle = 0, size = 12, face = 'bold', vjust = 1),
    
    axis.text.x = element_text(angle = 90, size = 14, face = 'bold', hjust = 1.0, vjust = 0.5),
    axis.text.y = element_text(angle = 0, size = 12, face = 'bold', vjust = 0.5),
    axis.title = element_text(size = 14, face = 'bold'),
    axis.title.x = element_text(size = 14, face = 'bold'),
    axis.title.y = element_text(size = 14, face = 'bold'),
    axis.line = element_line(colour = 'black'),
    
    #Legend
    legend.key = element_blank(), # removes the border
    legend.key.size = unit(1, "cm"), # Sets overall area/size of the legend
    legend.text = element_text(size = 14, face = "bold"), # Text size
    title = element_text(size = 14, face = "bold")) +
  coord_flip()
```































#look at greenyellow and light cyan are worth a closer look. Greenyellow is similar between M&F, but light cyan is opposite direction between the sexes.

```{r}
MEtrait = read_excel("/Users/kchau/Documents/PEBBLES/sampletraits/FolicAcidM_F_Placenta_combinations.xlsx")
#MEtrait <- MEtrait[, -c(4)]

MEtrait$PCB_dose[MEtrait$PCB_dose == '0'] <- 'NO_PCB'
MEtrait$PCB_dose[MEtrait$PCB_dose == '1'] <- 'YES_PCB'
MEtrait$Folic_Acid[MEtrait$Folic_Acid == '0'] <- 'NO_FA'
MEtrait$Folic_Acid[MEtrait$Folic_Acid == '1'] <- 'YES_FA'

femaleMEtrait <- MEtrait %>% filter(MEtrait$Sex == "F")

#femaleMEtrait <- femaleMEtrait[-c(35),] #remove outlier 36_01

femaleME_blue_traits <- cbind(femaleMEtrait, eigengene = MET[[1]]$data$MEblue)

#femaleME_purple_traits$ <- as.factor(femaleME_purple_traits$PCB_dose)


femaleME_blue_traits$FA_PCB <- paste(femaleME_blue_traits$Folic_Acid, femaleME_blue_traits$PCB_dose, sep = "/")



femaleME_blue_traits$FA_PCB <- as.factor(femaleME_blue_traits$FA_PCB)
levels(femaleME_blue_traits$FA_PCB)

femaleME_blue_traits$FA_PCB <- factor(femaleME_blue_traits$FA_PCB, levels=c('NO_FA/NO_PCB', 'YES_FA/NO_PCB', 'NO_FA/YES_PCB', 'YES_FA/YES_PCB'))


ggplotblue_female <- ggplot(data = femaleME_blue_traits, aes(x = FA_PCB, y = MET[[1]]$data$MEblue, color = FA_PCB)) + geom_boxplot() + geom_point() + ggtitle("Female Placenta: Eigengene Values in Blue Module") + xlab("Folic Acid / PCB") + ylab("Module Eigengene Values") 

ggplotblue_female + geom_point(size=3) + ylim(-0.5, 0.5) + theme_classic() + theme(text = element_text(size=12)) + theme(axis.text=element_text(size=12, face = "bold"), axis.title=element_text(size=16,face="bold")) + theme(plot.title = element_text(face="bold")) + theme(plot.title = element_text(size=18)) + theme(plot.title = element_text(hjust = 0.5))
```
```{r}
femaleME_blue_traits$PCB_dose[femaleME_blue_traits$PCB_dose == "NO_PCB"] <- 0
femaleME_blue_traits$PCB_dose[femaleME_blue_traits$PCB_dose == "YES_PCB"] <- 0.1
```

```{r}
femaleME_blue_traits$Folic_Acid[femaleME_blue_traits$Folic_Acid == 'NO_FA'] <- 'No Folic Acid'
femaleME_blue_traits$Folic_Acid[femaleME_blue_traits$Folic_Acid == 'YES_FA'] <- 'Yes Folic Acid'
```

```{r}
#new plot
new_ggplotblue_female <- ggplot(data = femaleME_blue_traits) +
  aes(x = PCB_dose, y = eigengene, color = Folic_Acid) + 
  geom_boxplot(lwd = 1, position = position_dodge(width = 0.9)) + 
  geom_point(size = 3, position = position_dodge(width = 0.9)) + 
  geom_smooth(method = lm, se = FALSE, mapping = aes(group = Folic_Acid), position = position_dodge(width = 1)) +
  ggtitle("Female Placenta: Eigengene Values in Blue Module") +
  xlab("PCB (mg/kg/day)") + 
  ylab("Module Eigengene Values") +
  theme(axis.text=element_text(size=12, face = "bold"), axis.title=element_text(size=14,face="bold")) +
  theme(plot.title = element_text(face="bold")) +
  theme(text = element_text(size=12, face="bold")) +
  theme(plot.title = element_text(hjust = 0.5))

```

```{r}
new_ggplotblue_female + labs(color='Folic Acid') 
```






```{r}
maleMEtrait <- MEtrait %>% filter(MEtrait$Sex == "M")

maleME_blue_traits <- cbind(maleMEtrait, eigengene = MET[[2]]$data$MEblue)
maleME_blue_traits$PCB_dose[maleME_blue_traits$PCB_dose == "NO_PCB"] <- 0
maleME_blue_traits$PCB_dose[maleME_blue_traits$PCB_dose == "YES_PCB"] <- 0.1


#maleMEtrait <- maleMEtrait[-c(26,27),] #remove outlier 35_05 and 35_06



#femaleME_purple_traits$ <- as.factor(femaleME_purple_traits$PCB_dose)


maleME_blue_traits$FA_PCB <- paste(maleME_blue_traits$Folic_Acid, maleME_blue_traits$PCB_dose, sep = "/")



maleME_blue_traits$FA_PCB <- as.factor(maleME_blue_traits$FA_PCB)
levels(maleME_blue_traits$FA_PCB)

maleME_blue_traits$FA_PCB <- factor(maleME_blue_traits$FA_PCB, levels=c('NO_FA/NO_PCB', 'YES_FA/NO_PCB', 'NO_FA/YES_PCB', 'YES_FA/YES_PCB'))


ggplotblue_male <- ggplot(data = maleME_blue_traits, aes(x = FA_PCB, y = MET[[2]]$data$MEblue, color = FA_PCB)) + geom_boxplot() + geom_point() + ggtitle("Male Placenta: Eigengene Values in Blue Module") + xlab("Folic Acid / PCB") + ylab("Module Eigengene Values")

ggplotblue_male + geom_point(size=3) + ylim(-0.5, 0.5) + theme_classic() + theme(text = element_text(size=12)) + theme(axis.text=element_text(size=12, face = "bold"), axis.title=element_text(size=16,face="bold")) + theme(plot.title = element_text(face="bold")) + theme(plot.title = element_text(size=18)) + theme(plot.title = element_text(hjust = 0.5))

```

```{r}
maleME_blue_traits$Folic_Acid[maleME_blue_traits$Folic_Acid == 'NO_FA'] <- 'No Folic Acid'
maleME_blue_traits$Folic_Acid[maleME_blue_traits$Folic_Acid == 'YES_FA'] <- 'Yes Folic Acid'
```

```{r}
#new plot
new_ggplotblue_male <- ggplot(data = maleME_blue_traits) +
  aes(x = PCB_dose, y = eigengene, color = Folic_Acid) + 
  geom_boxplot(lwd = 1, position = position_dodge(width = 0.9)) + 
  geom_point(size = 3, position = position_dodge(width = 0.9)) + 
  geom_smooth(method = lm, se = FALSE, mapping = aes(group = Folic_Acid), position = position_dodge(width = 1)) +
  ggtitle("Male Placenta: Eigengene Values in Blue Module") +
  xlab("PCB (mg/kg/day)") + 
  ylab("Module Eigengene Values") +
  theme(axis.text=element_text(size=12, face = "bold"), axis.title=element_text(size=14,face="bold")) +
  theme(plot.title = element_text(face="bold")) +
  theme(text = element_text(size=12, face="bold")) +
  theme(plot.title = element_text(hjust = 0.5))

```

```{r}
new_ggplotblue_male + labs(color='Folic Acid') 
```


```{r}
#new plot
new_ggplotblue_male <- ggplot(data = maleME_blue_traits) +
  aes(x = PCB_dose, y = eigengene, color = Folic_Acid) + 
  geom_boxplot(position = position_dodge(width = 0.82)) + 
  geom_point(size = 3, position = position_dodge(width = 0.82)) + 
  geom_smooth(method = lm, se = FALSE, mapping = aes(group = Folic_Acid), position = position_dodge(width = 1)) +
  ggtitle("Male Placenta: Eigengene Values in Blue Module") +
  xlab("PCB (mg/kg/day)") + 
  ylab("Module Eigengene Values") +
  theme(text = element_text(size=11)) + 
  theme(axis.text=element_text(size=12, face = "bold"), axis.title=element_text(size=14,face="bold")) + 
  theme(plot.title = element_text(face="bold"))
```

```{r}
new_ggplotblue_male
```
```{r}
ConSex_Placentas_FA_genes_in_module <- joinGeneSymbol[ , c(4, 6)]
library(dplyr)
library(tidyr)
library(data.table)

ConSex_Placentas_FA_genes_in_module <- distinct(ConSex_Placentas_FA_genes_in_module) %>% 
  mutate(rn = rowid(ModuleColor)) %>%
  pivot_wider(names_from = rn, values_from = external_gene_name, 
    names_sep = "", values_fill = "")
    
library(tidyverse)

ConSex_Placentas_FA_genes_in_module <- ConSex_Placentas_FA_genes_in_module %>% 
  column_to_rownames(var = "ModuleColor")   
  
ConSex_Placentas_FA_genes_in_module <- t(ConSex_Placentas_FA_genes_in_module)
    
ConSex_Placentas_FA_genes_in_module <- as.data.frame(ConSex_Placentas_FA_genes_in_module)



writexl::write_xlsx(ConSex_Placentas_FA_genes_in_module, "/Users/kchau/Documents/WGCNA/ConsensusPlacentaComparisonFolicAcid/ConSex_Placentas_FA_genes_in_module.xlsx")
```



